### ISSUE TITLE
Minecraft Crash #1

### ISSUE THREAD

**Issue by JenniferGaming** [JenniferGaming/Minecraft#1]
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 3/9/17 9:46 PM
Description: Ticking entity

java.lang.IllegalAccessError
	at net.machinemuse.powersuits.powermodule.movement.GliderModule.onPlayerTickActive(GliderModule.java:56)
	at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$1.apply(PlayerUpdateHandler.scala:46)
	at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$1.apply(PlayerUpdateHandler.scala:43)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:43)
	at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:40)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at net.machinemuse.powersuits.event.PlayerUpdateHandler.onPlayerUpdate(PlayerUpdateHandler.scala:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_29_PlayerUpdateHandler_onPlayerUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:459)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1563)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:117)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.World.func_72870_g(World.java:1831)
	at net.minecraft.world.World.func_72939_s(World.java:1663)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2089)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.machinemuse.powersuits.powermodule.movement.GliderModule.onPlayerTickActive(GliderModule.java:56)
	at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$1.apply(PlayerUpdateHandler.scala:46)
	at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$1.apply(PlayerUpdateHandler.scala:43)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:43)
	at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:40)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at net.machinemuse.powersuits.event.PlayerUpdateHandler.onPlayerUpdate(PlayerUpdateHandler.scala:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_29_PlayerUpdateHandler_onPlayerUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:459)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1563)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:117)
	at net.minecraft.world.World.func_72866_a(World.java:1862)
	at net.minecraft.world.World.func_72870_g(World.java:1831)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 37
	Entity Name: Elsa913
	Entity's Exact location: 123.50, 4.00, 329.50
	Entity's Block location: 123.00,4.00,329.00 - World: (123,4,329), Chunk: (at 11,0,9 in 7,20; contains blocks 112,0,320 to 127,255,335), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1663)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Elsa913'/37, l='MpServer', x=123.50, y=4.00, z=329.50]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 131.00,4.00,335.00 - World: (131,4,335), Chunk: (at 3,0,15 in 8,20; contains blocks 128,0,320 to 143,255,335), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1686 game time, 1204 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 7 total; [EntityHorse['Horse'/69476, l='MpServer', x=171.97, y=4.00, z=278.94], EntityCow['Cow'/69492, l='MpServer', x=95.50, y=4.00, z=283.50], EntityCow['Cow'/69478, l='MpServer', x=93.91, y=4.00, z=255.94], EntityRabbit['Rabbit'/69482, l='MpServer', x=131.50, y=4.00, z=396.50], EntityRabbit['Rabbit'/69485, l='MpServer', x=114.56, y=4.00, z=400.75], EntityPlayerSP['Elsa913'/37, l='MpServer', x=123.50, y=4.00, z=329.50], EntityCow['Cow'/69487, l='MpServer', x=166.50, y=4.00, z=362.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 286381280 bytes (273 MB) / 613965824 bytes (585 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJAAAA	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJAAAA	mantle{1.8.9-0.9.2.jenkins102} [Mantle] (Mantle-1.8.9-0.9.2.jar) 
	UCHIJAAAA	numina{0.4.0.131.jar} [Numina] (Modular-Powersuits-Mod-1.8.9.jar) 
	UCHIJAAAA	powersuits{1.0} [powersuits] (Modular-Powersuits-Mod-1.8.9.jar) 
	UCHIJAAAA	tconstruct{1.8.9-2.2.1.jenkins1005} [Tinkers' Construct] (TConstruct-1.8.9-2.2.1.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 5450'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

	Launched Version: 1.8.9-forge1.8.9-11.15.1.1902-1.8.9
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 5450 GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU E8500 @ 3.16GHz

**Comment by JenniferGaming** [comment]
This is a crash report, everytime I try to equip+upgrade my power suit/ power module, it crashes.

**Comment by JenniferGaming** [comment]
Help is greatly appreciated.
